services:
  database:
    image: mongo:7.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 256M
  cashe:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    command: >
      redis-server
        --maxmemory 256mb
        --maxmemory-policy allkeys-lru
        --appendonly yes
        --save 60 1000
    mem_limit: 300m

  api:
    build: 
      context: ./backend
      target: development
    environment:
      - NODE_OPTIONS=--max-old-space-size=350
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    deploy:
      resources:
        limits:
          memory: 400M

  web:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173" 
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 400M
